
############################################################           
##  R U N S
############################################################           
## A run is associated with an individual flow cell and contains metrics and reads generated by the instrument on which the flow cell was sequenced

setMethod("listRuns","AppAuth",
          function(x, id, ...) {
            
            if(missing(id))
              return(x$doGET(resource = "users/current/runs", ...))
            
            if(length(list(...)))
              warning("Query parameters ignored when quering selected runs!")
            
            res <- lapply(id, function(i) {
              x$doGET(resource = make_resource("runs", i))
            })
            
            if(length(id) == 1L) 
              res <- res[[1L]]
            else
              names(res) <- id
            
            return(res)
          })



